Feature/build-architecture
eeeeweeee/Gamenawa pull request #10
Opened 2022-10-03 11:15 UTC by gu-sil

**TL;DR**
`GamesController` - `GamesService`를 주축으로 기본 뼈대 구축

**참고**
- 테스트 코드 작성을 위해 `Mockito` 라이브러리 추가
- Json 파싱을 위해 `Gson` 라이브러리 추가
- 게임 이름, 제작사 등을 가져오는 `IGameInfoSearcher` 인터페이스를 따로 둠
    - **구현체를 만들때 스팀에 접속하는 빈이 `IGameInfoSearcher`와 `IGameScoreSearcher`를 모두 상속받으면 접속 한번에 필요한 정보를 가져오는 게 가능하긴 할 듯..?**
- 테스트 프로젝트가 아니라 스프링 프로젝트 실행이 안됨. `IGameInfoSearcher`의 구현체가 없기 때문. 더미 클래스를 추가하려다가 말았음. 테스트 코드는 Mock을 만들어서 테스트했음.
- 테스트 커버리지 100% (메소드, 라인 100%)

close #3

2022-10-03 13:00 UTC, Rabongbong requested changes
<Game controller파일> 
json이 null이면 bad_reqeust(400)보단 not found(404)로 가는게 좀 더 좋을꺼 같은데, 이 부분은 좀 더 얘기하는게 좋을꺼 같아요!!

2022-10-04 12:06 UTC, gu-sil commented
1. 400 -> 404로 고침
2. json으로 이름 지은 건 리턴하는게 json 포맷이란걸 강조하고 싶어서였는데, 어떻게 바꾸는게 좋을까? `result`는 return되는 객체라는 걸 보여줄 수 있다는 장점이 있는 것 같고, `score`는 실제로 점수말고도 다른 정보도 있는거라 사실과 다른 거라 안될 것 같아. 내 개인적인 생각으로는 코드가 짧아서 result로 리턴되는 객체라는 걸 알려주지 않아도 괜찮지 않을까 생각.
아니면 `gamesService.getGameByTitle(title);`를 `gamesService.getGameJsonByTitle(title)`로 바꾸고 결과를 받아내는 변수를 `result`로 할까?

2022-10-05 12:40 UTC, gu-sil commented
![Class Diagram](http://www.plantuml.com/plantuml/proxy?src=http://www.plantuml.com/plantuml/svg/ZP71oi8m3CVlVOhG1mZi-l4X0myoJyAUeDGC1rqhIVNamriipinUF1L--JNvD-qbEywt9PY3MqZsAMPE8H03uWw65no9xxCd-0EcoMpP_mCHD1cMQu2YpkKqJS5sjlIr7I96MzkFFZ6DvDXVYEkCzjuQPeXJ-aa-Ieednx9gcjJKogXnZGzE1BusOUQOYIVdQRiFRQlnMc_UfuegpxlJ1_GKp-LJdW00)

2022-10-05 12:55 UTC, Rabongbong commented
gamesService.getGameJsonByTitle(title)로 바꾸고 결과를 받아내는 변수는 다른걸로 하는게 나중에 유지보수 측면에서도 좋을꺼 같아!!
result라고 하면 결과값이라고만 아니깐 gameScores나 다른 변수명을 쓰는게 좋아보여요

2022-10-05 13:01 UTC, gu-sil commented
> gamesService.getGameJsonByTitle(title)로 바꾸고 결과를 받아내는 변수는 다른걸로 하는게 나중에 유지보수 측면에서도 좋을꺼 같아!! result라고 하면 결과값이라고만 아니깐 gameScores나 다른 변수명을 쓰는게 좋아보여요

`gameScores`는 점수만 있을 것 같은데, 실제로 게임 정보(이름, 장르 등)도 있어서 딴거로 하고 싶은데 애매하네

2022-10-05 13:29 UTC, Rabongbong commented
gameInfo로 해도 되지 않을까? 게임 정보에 장르와 score가 다 있잖아!!
그리고 Game이랑 GameScore가 VO라고 했는데 DTO가 아닌 VO를 쓴 이유가 있을까요??

2022-10-05 13:41 UTC, gu-sil commented
1. `gameInfo`는 `gameInfoSearcher`가 있어서 애매하더라고. 게임 점수 + 기타 정보를 합쳐서 `gameInfo`라고 하려면 기타 정보를 `gameDetail` 이나 그런 이름으로 바꿔야할 듯.
지금은 `Game` = `GameInfo` + `GameScore` 임.
2. `Game`과 `GameScore`는 DTO 이면서 VO 인데, VO라고 한 이유는 Setter가 없는걸 강조하고 싶었음.

2022-10-05 13:55 UTC, gu-sil commented
흠 일단 `gameJson`은 어때?

2022-10-05 14:04 UTC, Rabongbong commented
gameJson좋아
Game이랑 GameScore에서 @RequiredArgsConstructor Annotation썼는데 생성자를 자동으로 만들어 줘서 쓴거면 
```java
@Builrder
private GameScore(String score, String rate) {
    this.score = score;
    this.rater = rater
}
```
이렇게 builder쓰면 score랑 rate에 정확하게 데이터를 넣을 수 있을꺼 같아 형 의견은 어때??

2022-10-05 14:09 UTC, gu-sil commented
좋은 듯! 빌더 패턴은 일부분만 값 넣을때 쓰는 건줄 알았는데, 이렇게 쓰면 훨씬 유연해지네

2022-10-09 09:03 UTC, gu-sil commented
fix #14 #13 #12

2022-10-11 04:31 UTC, merged